export const REGISTER_REDIRECT_URL = 'REGISTER_REDIRECT_URL';
export const REGISTER_REDIRECT_MESSAGE = 'REGISTER_REDIRECT_MESSAGE';
export const CLEAR_REDIRECT_URL = 'CLEAR_REDIRECT_URL';
export const SET_USER_FOR_REGISTER = 'SET_USER_FOR_REGISTER';
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';
