export const UPDATE_BREAK_POINT = 'UPDATE_BREAK_POINT';
export const TOGGLE_MAIN_MENU = 'TOGGLE_MAIN_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';
export const TOGGLE_APP_LOADING = 'TOGGLE_APP_LOADING';
