export const UPDATE_BREAK_POINT = 'UPDATE_BREAK_POINT';
export const TOGGLE_MAIN_MENU = 'TOGGLE_MAIN_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';
export const TOGGLE_SEARCH_FORM = 'TOGGLE_SEARCH_FORM';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
