// layout
export const UPDATE_BREAK_POINT = 'UPDATE_BREAK_POINT';
export const TOGGLE_MAIN_MENU = 'TOGGLE_MAIN_MENU';
export const TOGGLE_SUB_MENU = 'TOGGLE_SUB_MENU';
export const TOGGLE_SEARCH_FORM = 'TOGGLE_SEARCH_FORM';
export const TOGGLE_USER_DROPDOWN = 'TOGGLE_USER_DROPDOWN';

// auth
export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL';
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL';
export const REDIRECT_TO_REGISTER = 'REDIRECT_TO_REGISTER';
export const REDIRECT_TO_LOGIN = 'REDIRECT_TO_LOGIN';
export const START_AUTH_PROCESS = 'START_AUTH_PROCESS';
export const STOP_AUTH_PROCESS = 'STOP_AUTH_PROCESS';
export const SET_USER_FOR_REGISTER = 'SET_USER_FOR_REGISTER';

// user
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const POST_EDIT = 'POST_EDIT';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_FAILURE = 'POST_EDIT_FAILURE';
export const POST_STAR = 'POST_STAR';
export const POST_STAR_SUCCESS = 'POST_STAR_SUCCESS';
export const POST_STAR_FAILURE = 'POST_STAR_FAILURE';
export const POST_DETAIL = 'POST_DETAIL';
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS';
export const POST_DETAIL_FAILURE = 'POST_DETAIL_FAILURE';

// Post list
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

// Create new post
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';
export const RESET_POST_PROPS = 'RESET_POST_PROPS';

// Fetch post
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

// Delete post
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

// Edit post
export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';

// Search Post
export const SEARCH_POSTS = 'SEARCH_POSTS';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
export const SEARCH_POSTS_FAILURE = 'SEARCH_POSTS_FAILURE';

// Create new post reply
export const CREATE_REPLY = 'CREATE_REPLY';
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS';
export const CREATE_REPLY_FAILURE = 'CREATE_REPLY_FAILURE';
export const RESET_NEW_REPLY = 'RESET_NEW_REPLY';

// Fetch boards
export const FETCH_BOARDS = 'FETCH_BOARDS';
export const FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS';
export const FETCH_BOARDS_FAILURE = 'FETCH_BOARDS_FAILURE';
