export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const REMOVE_USER = 'REMOVE_USER';
export const OPEN_USERINFO_MODAL = 'OPEN_USERINFO_MODAL';
export const CLOSE_USERINFO_MODAL = 'CLOSE_USERINFO_MODAL';
